### ISSUE TITLE
Post-release TODO

### ISSUE THREAD

**Issue by blitzmann** [blitzmann/lpStore#3]
These are ideas that need further refinement after the initial (re)release of lpStore.
- [ ] History tab for offers
  - Shows the isk/lp of offer over time. I am already keeping track of data in personal table that is not included with LPDB (`lpTracking`), however it's still based on old code and is updated every 6 hours. 
    - Store history data from EMDR feed, which will eat up a lot of space, or
    - Possibly gather history data from third party and calculate within a certain time frame. This can be cached locally and only new data could be fetched afterwards.
- [ ] Utility functions on corp offers page:
  - Clickable Icons
  - Link to eve-central or other market site
  - Show required items without refreshing to offer page (possibly get offer page via `/json` API)
  - Show pricing info
  - Show Info (if IGB, open show info, if not, open dialog with ajax content)
- [ ] Shopping cart
  - Click offers -> add qty to shopping cart (can also do "Add #### worth of LP" or any variation). Shopping cart will list all items, how much LP and ISK is needed.
  - Store shopping cart in Cookie, or local browser storage? Undecided. Do NOT want to make user accounts.
- [ ] Find place for Price Caching information. I removed it colored indicator from the old lpStore for aesthetic reasons. Not sure if it was actually used... Possibly provide a sort of cache index (weighted value based on offer's cache and required items) and have it in the corp offers page, but hidden by default. Can have the actual hours listed on the offer page in small text next to items (ie: updated 2 hrs ago)
- [ ] Conversion store (CONCORD/Incursion conversion). Problem with this is the need to calculate ALL offers as CONCORD LP can be used with all stores (except FW It hink?). Possibly cache LpOffer data if possible and adjust based on conversion rate, use cached data ONLY for concord store. Or, cache concord store for 1-2 days. Worse case- calculate on the fly, which will take 3-5 seconds. More thought required. 
  - OR, is it necessary? Since most stores convert at the same rate (80% I think), the offers will still be the same relative to each other. A offer that is 1500 ISK/LP in the regular store might be 1300 ISK/LP converted, but all other offers will show the same reduction o their ISK/LP. So, simply find a offer that you like and convert to that store, just understanding that ISK/LP will be less since you convert.
